### ISSUE TITLE
Web Sockets or ENet-CSharp?

### ISSUE THREAD

**Issue by valkyrienyanko** [valiafetisov/unity-webgl-multiplayer#4]
I'm wondering what your opinion is on the difference between Web Sockets and [ENet-CSharp](https://github.com/nxrighthere/ENet-CSharp). Knowing that ENet exists, if you were to create another networking model, would you stick with Web Sockets or go with ENet? And what would be the reason behind your choice?

**Comment by valiafetisov** [comment]
Hey @valkyrienyanko, the repository is a boilerplate for a WebGL build, not for the general multiplayer networking. Therefore its primary target is the browser with built-in support for [WebSocket](https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API). Simple Web Sockets plugin provided by Unity was chosen because it not only works in the browser, but provides C# fallback during development.

Therefore, if your primary build target is not a browser, consider using something else.
